### ISSUE TITLE
Implement EIP-2535 to make workgroup shield contract upgradeable

### ISSUE THREAD

**Issue by kthomas** [eea-oasis/baseline#256]
## Overview

The "Diamond Standard" (see [EIP-2535](https://eips.ethereum.org/EIPS/eip-2535)) is a pattern for upgradable smart contracts. The workgroup shield contract should be refactored to implement EIP-255, with each workflow identifier becoming an upgradable [facet](https://eips.ethereum.org/EIPS/eip-2535#facets-and-state-variables).

### Reference

- [EIP-2535](https://eips.ethereum.org/EIPS/eip-2535)

### Questions

- How do existing workflows behave once they are upgraded?

## Tasks

- [ ] Spike the workgroup shield contract diamond pattern

**Comment by Therecanbeonlyone1969** [comment]
A couple of comments/thoughts/observations:
- You need all contracts to be facets in the diamond pattern, not just the shield contract
- You need the governance contract from the Diamond pattern to manage the upgrade process
- Since during the upgrade process you need to suspend processing, you need 
    a. a transaction queue
    b. a mechanism that pends transactions in the queue when the upgrade is initiated
- You need a way to roll back an upgrade if a bug is found which would be most simply done through another upgrade process  
- You need to be able to inform the users of a planned upgrade and you need to inform users that a transaction is pending due to upgrade -- requires additional request response for transaction submission
- Since you have shared storage e.g. workgroups etc. you need to utilize the diamond pattern where contracts share storage (separate contract instances for functional vs storage contracts)
- Who or what will be authorized to make upgrades?

**Comment by ognjenkurtic** [comment]
@Kasshern @skosito @Ybittan @biscuitdey This discussion might be relevant for our work on the SRI. Keeping it open so that we can discuss.

**Comment by Therecanbeonlyone1969** [comment]
Trail of Bits brought up [significant security issues](https://blog.trailofbits.com/2020/10/30/good-idea-bad-design-how-the-diamond-standard-falls-short/) with EIP-2535, [and the response](https://dev.to/mudgen/addressing-josselin-feist-s-concern-s-of-eip-2535-diamond-standard-me8).

[More real-world use cases and a Consensys Diligence recommendation](https://eip2535diamonds.substack.com/p/what-people-say-about-the-diamond)

[Real-world use case](https://coinyuppie.com/analysis-of-eip-2535-diamond-protocol-from-the-saudis-incident/) and security analysis of that implementation.

[Recent blog about EIP-2535](https://soliditydeveloper.com/eip-2535) ... apparently 3 reference implementations by author have been security audited.

@ognjenkurtic @Kasshern @Ybittan @biscuitdey @kthomas

**Comment by skosito** [comment]
> @Kasshern @skosito @Ybittan @biscuitdey This discussion might be relevant for our work on the SRI. Keeping it open so that we can discuss.

probably not so relevant for us, but if we decide to make contracts upgradable since we will use hardhat anyways we can use proxy pattern built in hardhat https://docs.openzeppelin.com/upgrades-plugins/1.x/hardhat-upgrades
